version: "2"
linters:
  default: all
  disable:
  # these linters are disabled either because they
  # are annoying or because they are deprecated
  - cyclop
  - err113
  - exhaustive
  - exhaustruct
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocyclo
  - godox
  - gomoddirectives # need replacements for wasip1
  - inamedparam
  - ireturn
  - mnd
  - nestif
  - nonamedreturns
  - tagliatelle
  - testpackage
  - varnamelen
  settings:
    depguard:
      rules:
        main:
          deny:
          - pkg: gopkg.in/yaml.v2
            desc: use yaml.v3 only
    gocritic:
      disabled-checks:
      - hugeParam
      enabled-checks:
      - filepathJoin
      - dupImport
      - redundantSprint
      - stringConcatSimplify
      enabled-tags:
      - performance
    govet:
      disable:
      - shadow
      # this is nice, but it doesn't seem possible to disable
      # this for tests? definitely don't want this in tests
      - fieldalignment
      enable-all: true
    perfsprint:
      err-error: true
    revive:
      rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        arguments:
        - allowRegex: ^_
        severity: warning
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
      - name: unused-receiver
        arguments:
        - allowRegex: ^_
        severity: warning
        disabled: false
    staticcheck:
      checks:
      - all
    tagliatelle:
      case:
        rules:
          json: snake
  exclusions:
    rules:
    - path: '(.+)_test\.go'
      linters:
      - forcetypeassert
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - scanner.go
    - tokens.go
    - internal/lsp/opa
formatters:
  enable:
  - gci
  - gofmt
  settings:
    gci:
      sections:
      - standard
      - default
      - prefix(github.com/charlieeagn3/immich-manager)
      - blank
      - dot
